sudo: required
services:
  - docker
before_install:
  - docker build -t nikitosis/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true nikitosis/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-north-1-594263087233"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY